title: VIDIT JAIN
logo: /images/mrs.png
description: Data Science and Analytics Enthusiast and currently a final year Master's student at IIT Delhi

Deeply passionate individual who aspires to uncover the hidden connections within complex data. Tries to connect the dots in every experience.
theme: jekyll-theme-minimal
# theme: jekyll-theme-Midnight
