title: VIDIT JAIN
logo: /images/img4.png
description: 
Data Science and Analytics Enthusiast and currently a final year Master's student at IIT Delhi
E-Mail - contact.viditjain@gmail.com
Conatct - 9911180396
E-Mail: contact.viditjain@gmail.com
Conatct: 9911180396
theme: jekyll-theme-minimal
# theme: jekyll-theme-Midnight
