title: VIDIT JAIN
logo: /images/img.png
description: Data Science and Analytics Enthusiast and currently a final year Master's student at IIT Delhi
theme: jekyll-theme-minimal
# theme: jekyll-theme-Midnight
