title: VIDIT JAIN
logo: /images/img4.png
description: Currently a final year Master's student at IIT Delhi. Deeply passionate individual who aspires to uncover the hidden connections within data driven world. Email- contact.viditjain@gmail.com contact- 9911180396 
theme: jekyll-theme-minimal
# theme: jekyll-theme-Midnight
