title: VIDIT JAIN
logo: /images/img4.png
description: 
Currently a final year Master's student at IIT Delhi. Deeply passionate individual who aspires to uncover the hidden connections within data driven world.
theme: jekyll-theme-minimal
# theme: jekyll-theme-Midnight
